### ISSUE TITLE
Sieve. Too much too soon? Gigasecond. Who struggles?

### ISSUE THREAD

**Issue by fish-ter** [exercism/xrust#112]
As a Rust beginner, I found the `Sieve` exercise to be quite tough at that point in the track.

My solution ended up being quite terse, but that doesn't convey the sense of struggle involved, and it feels like an unexpected holiday when you hit `Gigasecond` (aka `HelloWorld 2: the revenge which is even less scary than the first time around`).

Probably the biggest offender in my opinion is `Gigasecond`. The ordering of `Sieve` related to other subsequent exercises is quite hard to pinpoint, and perhaps I was having a bad brain day.

**Comment by IanWhitney** [comment]
Gigasecond, considering its simplicity, comes way too late. It's mostly included as a way to introduce Crates and reading their documentation.

When we [introduced Sieve](https://github.com/exercism/xrust/pull/97) we talked about placement and weren't sure. I thought it worked well after the iterator usage that were part of Anagrams and Difference of Squares. But maybe the leap is too big.

Looking at most people's Sieve implementations, I think there are two things they are missing: good higher-order-function usage and good looping usage. If there's a problem that does a better job of introducing one or two of those concepts, then maybe we should move Sieve after it?

**Comment by kytrinyx** [comment]
> HelloWorld 2: the revenge which is even less scary than the first time around

LOL. I love it. In Go we have Gigasecond as the fourth problem ("hello-world", "leap", "clock", "gigasecond"). It works well as a "first-ish" exercise (though in Go people can struggle a bit with type conversions and the concept of Duration, so it's not quite Hello World the Revenge for some folks).

**Comment by petertseng** [comment]
I was going to say "Queen attack probably has looping when showing the board!" but we don't do board display. Somewhere in the neighborhood of beer song and minesweeper?

**Comment by fish-ter** [comment]
Initially I was attempting a purely functional approach to `Sieve`, and yet I see that it's waaay down the list in the Haskell exercises. If others are trying alternative approaches, they might not experience brain cell attrition at the same rate.

If there's not a good candidate amongst the existing exercises, is there a precursor that could be ported from another track?

@kytrinyx  Thx for what you've created!
@rest Thx for helping improve it!

**Comment by IanWhitney** [comment]
Ok, moving gigasecond is easy and ready to go in #115.

As for sieve, I'm not sure where it goes. Maybe after the nucleotide ones?

**Comment by petertseng** [comment]
I might consider right before or right after minesweeper, but I'm not sure on that.

I have half a mind to make a thing that compares exercise ordering across different tracks, though I need to think about how it should work first.

* Checking absolute number doesn't make much sense because tracks have different numbers of problems.
* Maybe I normalise by dividing by the number of exercises in the track? Could work, would have to see. May have weird results for tracks that tended to implement easier problems or harder problems. Probably a good first iteration.
* Maybe check all-pairs and see which pairs are most controversial (most even split?)? I wonder if all-pairs would be expensive to compute, but if we only have ~100 exercises total maybe it's not so bad...
