### ISSUE TITLE
Passing a tuple to new in Queen attack exercise feels weird 

### ISSUE THREAD

**Issue by ijanos** [exercism/xrust#118]
Passing a pair to a `new` function feels unidiomatic.

There is a discussion started on the site: 
http://exercism.io/submissions/05c66333b1b44c12a224e8fe4884a50d

We can continue here.

**Comment by petertseng** [comment]
For me personally I think y'all have convinced me. Passing two tuples to a function might make sense to show the more logical grouping, but a single tuple seems an unnecessary extra level of grouping (and I still believe that despite the fact that you can [destructure in the argument list](https://play.rust-lang.org/?code=fn%20foo((x%2C%20y)%3A%20(i32%2C%20i32))%20%7B%0A%20%20%20%20println!(%22%7B%7D%2C%20%7B%7D%22%2C%20x%2C%20y)%3B%0A%7D%0A%0Afn%20main()%20%7B%0A%20%20%20%20foo((3%2C%204))%3B%0A%7D&version=stable&backtrace=0))

**Comment by IanWhitney** [comment]
Here was my thought process when making that a tuple.

1. A co-ordinate on the board is the same as a point on a grid.
2. A point on a grid is the canonical example of a (data clump)[http://martinfowler.com/bliki/DataClump.html]
3. You get rid of data clumps by encapsulating them.
4. The simplest way to do that in this exercise was with a tuple.

I don't quite follow the argument that passing in a single tuple is odd. This could be an idiomatic thing in Rust (or systems languages) that I'm unfamiliar with. I feel the same way about passing tuples into new. Seems fine to me, but there may be an idiomatic reason to not do so.

Also, from a design perspective, one of the more interesting things about the current Queen Attack is what you do with the tuple once you pass it in. Yes, you can just use it as a tuple, or you can [encapsulate it, name it and give it behavior](http://exercism.io/submissions/56bc90c9fd30470fb09c305d26a2195c)

**Comment by petertseng** [comment]
To me it sounds like there are two points of view that make sense based on the context.

---

*In isolation*, one may see the tuple as an unneeded extra level of grouping. It's possible to say "if all the `Queen` tests are just testing queens with certain ranks and files that are sourced form somewhere we need not care about, why should it be that they values passed to us get packed up in a tuple? Especially if I'm just going to have to unpack the tuple immediately to operate on its two members anyway?"

---

On the other hand, *as part of a larger system that may pass coordinate points around*, tuples make sense if tuples are the representation of the coordinate points (and they indeed are a very reasonable representation).

If I had a list of coordinates that I wanted to turn into queens, it's likely that I would want to have them as a list of `(i8, i8)`, rather than two lists of `i8`.

And only if `Queen::new` takes a single `(i8, i8)` can you do something like `Queen::new(give_me_some_coordinates())` (obviously `give_me_some_coordinates()` would be some function that gives you an `(i8, i8)`). I currently do not know of a way to make this work if `Queen::new` was `(rank: i8, file: i8)`, and [my attempts on the playground were unsuccessful](https://play.rust-lang.org/?code=fn%20print_tuple((x%2C%20y)%3A%20(i32%2C%20i32))%20%7B%0A%20%20%20%20println!(%22%7B%7D%2C%20%7B%7D%22%2C%20x%2C%20y)%3B%0A%7D%0A%0Afn%20print_args(x%3A%20i32%2C%20y%3A%20i32)%20%7B%0A%20%20%20%20println!(%22%7B%7D%2C%20%7B%7D%22%2C%20x%2C%20y)%3B%0A%7D%0A%0Afn%20give_tuple()%20-%3E%20(i32%2C%20i32)%20%7B%0A%20%20%20%20(4%2C%205)%0A%7D%0A%0Afn%20main()%20%7B%0A%20%20%20%20%2F%2F%20Any%20way%20to%20get%20this%20to%20work%20in%20Rust%3F%0A%20%20%20%20%2F%2Fprint_args(give_tuple())%3B%0A%0A%20%20%20%20print_tuple(give_tuple())%3B%0A%7D%0A&version=stable&backtrace=0); I don't think Rust has a splat operator that will splat the tuple in in that case.

**Comment by petertseng** [comment]
Another potential thought: Maybe I didn't want to internally represent a position as a tuple! Notice that earlier I said (with emphasis added):

>  tuples make sense **if tuples are the representation of the coordinate points**

What if the conditional in that sentence were false? What if I wanted to represent my position as a struct with named members instead of a tuple? I'm out of luck, it has to be a tuple since that's what `Queen::new` expects.

If the exercise would separate out the "Create and validate a position given a rank and file" versus "Given a queen at a certain position, can it attack a queen at this other position", we could envision a world where students are free to choose whatever internal representation of position makes sense. My memory is getting a bit fuzzy, but I think that was one of the iterations considered [when Queen Attack was implemented for Rust](https://github.com/exercism/xrust/pull/89) but there was a concern about - how do we order the tests in a good way to allow the student to get to the first passing test quickly and iterate quickly from there?

I'll review the discussion around the initial implementation and see if I get any ideas.

**Comment by kytrinyx** [comment]
>  we could envision a world where students are free to choose whatever internal representation of position makes sense

That's the winning argument as far as I'm concerned. (Of course, I wouldn't be surprised if you had an argument tomorrow that convinced me of the opposite, but still. This is a good one.)

> the tests would get a bit more verbose

I'm personally OK with that, if it allows more freedom at the level of the implementation.

**Comment by IanWhitney** [comment]
>>  we could envision a world where students are free to choose whatever internal representation of position makes sense

> That's the winning argument as far as I'm concerned. (Of course, I wouldn't be surprised if you had an argument tomorrow that convinced me of the opposite, but still. This is a good one.)

I'm not sure I follow. How would this look? Since the tests would include functions with specific signatures, I don't see how students could choose their own internal representations.

**Comment by petertseng** [comment]
Yeah, you've essentially got it. Note that, whereas currently `Queen::new` returns a `Result`, I would think `ChessCoord` (which I might bikeshed as `Position`, but eh) return a `Result`. `Queen::new` would take an unconditional `ChessCoord` and unconditionally return a `Queen`, so the assumption is `ChessCoord`s can only hold valid chess coordinates.

**Comment by IanWhitney** [comment]
Coord is a terrible name, I just threw it there for an example. I can put together a sample of this and we can see if we like it.

**Comment by IanWhitney** [comment]
@petertseng When you say that `Queen::new` takes an unconditional Position, I'm not sure exactly what you mean. Do you think the tests will look like:

```rust
fn test_queen_creation() {
  let position = ChessPosition::new(1,2);
  let queen = Queen::new(position.unwrap());
  //etc.
}
```

**Comment by petertseng** [comment]
> When you say that Queen::new takes an unconditional Position, I'm not sure exactly what you mean. Do you think the tests will look like:

Yup, this tells me I should accompany my suggestions with code (I would have were I not otherwise occupied), but you do have the right of it.

**Comment by IanWhitney** [comment]
What do you think, @ijanos?

**Comment by petertseng** [comment]
I am usually cautious about speaking for others, but notice the thumbs up on https://github.com/exercism/xrust/issues/118#issuecomment-215800847 and who it comes from

**Comment by ijanos** [comment]
Sorry for the late response, I'm from Europe and I guess that is responsible for the longer delays between messages, you are sleeping while I'm awake an vice versa :)

@IanWhitney I like your proposed code, I think it is a better API for this exercise.

**Comment by kytrinyx** [comment]
BTW: I mentioned this conversation in today's "Behind the Scenes" newsletter. http://tinyletter.com/exercism/letters/exercism-it-s-about-the-conversations
