### ISSUE TITLE
Can `Anagram` be changed to either require or prevent Lifetimes?

### ISSUE THREAD

**Issue by IanWhitney** [exercism/xrust#166]
In #126, Anagram was the main reason we restructured our problem track. In that restructuring I grouped all of the "Lifeteme" problems together and moved them to be much later in the track.

But [you can pass the Anagram test suite without lifetimes](http://exercism.io/submissions/ff6c6d32c9184214a769b12ce28faec4). Which, if I'd thought about it for more than 2 seconds, I may have realized.

I'm wondering if there's a way to change the Anagram test suite to either require or prevent a solution that uses lifetimes. And, if so, would we want to.

#### Pros
- Lets us position the problem more exactly
- Lets us use the problem as a way to teach Lifetimes (assuming we force lifetimes)

#### Cons
- Forces an implementation

If this is possible, then I'm also wondering if we could provide 2 test suites, one with Lifetimes & one without, so that students could see both in action.

**Comment by kotp** [comment]
The possibility to include more than just the test, readme and example file is "built in" because only the example file is not transferred on fetch.

If one test is called `_with_lifetimes.ext` I think that may be as simple as possible.  The `README` for the track's exercise could explain what that is for and how to use it.

The Ruby track is talking about how to use an additional testing framework, and this may be one way to attack that problem.

**Comment by IanWhitney** [comment]
Good to know that it's possible on the Exercism side. I'm just not sure it's possible to do this with the Rust language itself.

**Comment by petertseng** [comment]
Yeah it's probably possible to write tests in such a way that a lifetime annotation is required. I can't think of how to do this right now, but I feel it should be possible given that there are many times when code won't compile without a lifetime annotation. On the other hand, maybe I'm wrong about that, since anything we would do that might eem to require lifetime annotations might be worked around by simply making a copy and taking ownership of the copy. I will need more time to reason about that.

On the other hand, I'm not sure it's possible to make it so that code compile without lifetime annotations and fails to compile with. but I'm also not sure what value that would have anyway.

If we are able to devise something that requires solutions to have a lifetime annotation, it would probably be good to have some exercise dedicated to showing that. Whether anagram has to be the exercise to demonstrate lifetimes remains to be seen. It certainy is a strong candidate since takes in some strings and returns some of the input strings (again, though, someone could just make a copy). That also means https://github.com/exercism/x-common/blob/master/strain.md is a possibility.

**Comment by jonasbb** [comment]
I think Strain would be ideal to force someone to use lifetimes. Maybe you need to split up Strain into a simple case (e.g. only numbers which are copy-able) and one which is fully generic. The fully generic one cannot assume the parameters to implement `Copy` or `Clone` so it has to use lifetimes.
