### ISSUE TITLE
Implement Acronym

### ISSUE THREAD

**Issue by IanWhitney** [exercism/xrust#180]
The problem is described in [its readme](https://github.com/exercism/x-common/blob/master/acronym.md)

- [ ] Use the [standard test definition](https://github.com/exercism/x-common/blob/master/acronym.json) as the basis for test/acronym.rs file
- [ ] Create an `example.rs` solution
- [ ] Place the problem in `config.json`
- [ ] Place the problem and describe its topics in `problems.md`

**Comment by gregcline** [comment]
I could try taking this on if you want.

**Comment by IanWhitney** [comment]
Awesome!

**Comment by petertseng** [comment]
For this issue, and all others of its kind: we need to update the readme and json links to point to their post re-organisation locations.

**Comment by petertseng** [comment]
about my above comment: Don't worry @gregcline what I said doesn't prevent you from taking it on, it just tells us that you need to find the README at https://github.com/exercism/x-common/blob/master/exercises/acronym/description.md and the test data at  https://github.com/exercism/x-common/blob/master/exercises/acronym/canonical-data.json , everything else is the same

**Comment by gregcline** [comment]
Yeah I noticed that before I commented, I was able to find them. Thanks for those links though.

**Comment by gregcline** [comment]
So I'm not sure where y'all would like this placed within `problems.md`. It feels like an introduction section problem to me, but it will be different from many other languages due to Rust not having regexes in the standard library. As a result the example solution I came up with is a little hairy when solving the camel case test.

Also, is the order the problems fall in the `config.json` the order they're presented to users?

**Comment by petertseng** [comment]
> So I'm not sure where y'all would like this placed within `problems.md`.

Sometimes I'm not sure until I see an implementation, so you are free to share the implementation first and we can work on deciding together.

However, if you were to ask me to guess by imagining what kind of solution I would write:
I'd either iterate over the characters and keep some state (was the last one whitespace? was it capital?) or split up the input by words and pull off the relevant characters from each word. I'd probably place somewhere in the neighbourhood of difference-of-squares through pangram. Happy to be convinced otherwise!

> Also, is the order the problems fall in the `config.json` the order they're presented to users?

Yes, exactly. Erm, I wish there were a piece of documentation I can point to that confirms this (well, OK, I could find code if I wanted to, but that's different); best I can do is say https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md#track-anatomy and it says "It contains configuration for which exercises (and in which order)". Anyway, yes, the order in `config.json`!

**Comment by gregcline** [comment]
So here's the example solution I came up with, please feel free to suggest improvements. Sorry if you would have preferred this in a PR or something. This is the first time I've tried contributing to open source and I'm still learning the git/github workflow.

```
#[allow(unused_variables)]
pub fn abbreviate(phrase: &str) -> String {
    phrase.split(|c: char| c.is_whitespace() || !c.is_alphanumeric())
          .flat_map(|word| split_camel(word))
          .filter(|word| !word.is_empty())
          .map(|word| word.split_at(1).0.to_uppercase())
          .collect::<String>()
}

fn split_camel(phrase: &str) -> Vec<String> {
    let chars: Vec<char> = phrase.chars().collect();
    let mut words: Vec<String> = Vec::new();
    let mut prev_ind: usize = 0;
    for (i, c) in chars.iter().enumerate() {
        if i > 0 && chars.len() > 0 && i == chars.len() - 1 {
            words.push(chars[prev_ind..i + 1].iter().cloned().collect());
        } else if i > 0 && c.is_lowercase() && chars[i + 1].is_uppercase() {
            words.push(chars[prev_ind..i + 1].iter().cloned().collect());
            prev_ind = i + 1;
        }
    }
    words
}
```

**Comment by petertseng** [comment]
It is useful if you specify `rust` after the three backticks so we have syntax highlighting (I added it for you). Alternatively, in a PR, we automatically get syntax highlighting.

We also gain the ability to comment on specific lines if it were a PR.

At first glance:

* I'd try to see whether the two instances of `words.push(chars[prev_ind..i + 1].iter().cloned().collect());` can be deduplicated.
* If `chars.len() == 0`, the body of the for loop is run zero times, therefore the check for `chars.len() > 0` inside it will always be true.

**Comment by petertseng** [comment]
Completed by #204 - thanks!
