### ISSUE TITLE
include a gitignore file in exercises

### ISSUE THREAD

**Issue by ashleygwilliams** [exercism/xrust#192]
hey team!

i like keeping track of my work (even for exercises) on github. it'd be awesome if the exercises came with a `.gitignore` file (containing at least the `target` directory). this would make it very easy for students to store their work on github, and would also teach them what a good rust `.gitignore` looks like.

thanks for all you do! 🐶 🐬 ✨

**Comment by petertseng** [comment]
You know, this is when I think it would be great if we could have support for https://github.com/exercism/x-api/issues/29 so that we can have a language-wide gitignore that gets delivered to students at `$EXERCISM_DIR/rust/.gitignore`, instead of `$EXERCISM_DIR/rust/$EXERCISE_SLUG/.gitignore`

This is because I suspect that students are more likely to want to store all their Rust exercises in single repo, rather than one repository per exercise.
