### ISSUE TITLE
Function interfaces for tests

### ISSUE THREAD

**Issue by andrey-gvrd** [exercism/xrust#64]
I was having a lot of issues trying to guess what kind of object is required to be passed in the allergies exercise.
I figured this is what it looked like:

    pub struct Allergies {
        score: i32,
    }

    impl Allergies {
        pub fn new(n: i32) -> Allergies {
            Allergies { score: 0 }
        }
    }

So I was basically trying to figure out what the `Allergies(0)` function did and where it came from.
In the end I had to resort to looking into the solution in `example.rs`, which is kind of upsetting.

Turns out the struct has the form `pub struct Allergies(pub usize);` and the `Allergies(0)` is... I still don't understand what it is and where it comes from.

Do you think there is a way to expose the interface without giving out the solution?

**Comment by kytrinyx** [comment]
@stevejb71 @petertseng @NobbZ -- do you have any ideas about how we could solve this?

**Comment by NobbZ** [comment]
To be honest, this is the exercise I'm stuck with too, I don't even know
why I'm called in here 😁

But yes, here the tests do a very strongly depend on the data structure
where possibly is no need for.

Also for the sake of the exercise it should not matter if you use the named
fields or tuple syntax.

Anyway, I will take a closer look tomorrow when I'm back at my laptop and
no one else chimed in.

Katrina Owen <notifications@github.com> schrieb am Mo., 11. Jan. 2016 20:26:

**Comment by kytrinyx** [comment]
@NobbZ I called you because you've commented a lot in the rust track :)

**Comment by andrey-gvrd** [comment]
A reasonable approach is taken [here](https://github.com/exercism/xrust/blob/master/robot-name/tests/robot-name.rs).

**Comment by kytrinyx** [comment]
Yeah, that looks good.

**Comment by petertseng** [comment]
Yeah, the expected interface being thrown in a comment somewhere seems good. Probably in the stub file would be in a more visible location than the test file, even?

On a related note, I've been trying to think about getting tests to be less constraining of implementation details these days. Do you think doing `Allergies(0)` is too constraining and it should be `Allergies::new(0)` instead?

(and the example impl can just have `fn new(n: uint) -> Allergies { Allergies(n) }` or similar, and anyone else can do whatever they want)

**Comment by NobbZ** [comment]
Yeah, one could give a list of functions and signatures in the impl, thats one good thing, but not the solution to the OPs problem.

The OP assumed the design of the type would be as usual. So he designed a struct using record-syntax and used a static function ``new`` in the impl to create new values of the type. This is quite a common pattern in rust.

There is another kind of structs, using tuplesyntax. There fields don't have a name, and the structs name is used as if it were the ``new`` function.

Both have some pros and cons, eg tuplesyntax is much nicer to pattern match on, while recordsyntax is much more self documenting due to the named fields.

I have seen both in the wild, but the section about tuple syntax in the official rust manual is very short, while record syntax is explained exhaustively.

So I'd prefer to not make any assumption in any future tests that make assumptions about the used syntax, but always use a static constructor in the impl and document signature as shown above.

**Comment by petertseng** [comment]
> So I'd prefer to not make any assumption in any future tests that make assumptions about the used syntax, but always use a static constructor in the impl and document signature as shown above.

Agree.
