### ISSUE TITLE
Logic behind an allergies test

### ISSUE THREAD

**Issue by andrey-gvrd** [exercism/xrust#65]
@adolfosilva 

What is the logic behind this test?

    #[test]
    fn test_ignore_non_allergen_score_parts() {
        assert_eq!(vec![Allergen::Eggs], Allergies(257).allergies());
    }

I'd understand if this test expected an empty vector since the score cannot be constructed out of a sum of `Allergen` values, by I can't figure out why `Allergen::Eggs` are expected to get through.

**Comment by adolfosilva** [comment]
I don't quite remember what this test was supposed to do due to lack of documentation and from being a translation from some other language.

The score can be the sum of all the Allergen index values (starting at 1) which would be equal to 255 and that test is covered. With a value of 257, we get a result that's essentially Allergies(1) (256 counts as 0). Allergies(258) would be Allergies(2) and so on...

Sorry that i can't be of more help than this.

**Comment by andrey-gvrd** [comment]
That would make sense if your system's `usize` was 8 bits)

**Comment by kytrinyx** [comment]
The idea behind this exercise was to introduce the idea of bitmasks.

**Comment by andrey-gvrd** [comment]
Wow, that part went completely over my head.
