### ISSUE TITLE
Explanation of tests in anagram

### ISSUE THREAD

**Issue by erip** [exercism/xrust#86]
I'm working on the anagram problem and my code is failing on these three tests:

```rust
#[test]
fn test_does_not_detect_a_word_as_its_own_anagram() {
    let inputs = ["banana"];
    let outputs: Vec<&str> = vec![];
    assert_eq!(anagram::anagrams_for("banana", &inputs), outputs);
}

#[test]
fn test_does_not_detect_a_differently_cased_word_as_its_own_anagram() {
    let inputs = ["bAnana"];
    let outputs: Vec<&str> = vec![];
    assert_eq!(anagram::anagrams_for("banana", &inputs), outputs);
}

#[test]
fn test_does_not_detect_a_differently_cased_unicode_word_as_its_own_anagram() {
    let inputs = ["ΑΒγ"];
    let outputs: Vec<&str> = vec![];
    assert_eq!(anagram::anagrams_for("ΑΒΓ", &inputs), outputs);
}
```

I think these tests should actually be `panic` because these assertions are not true if considering case insensitive code for the latter two and simply because there's no output for the trivial case of a self-describing anagram. 

Perhaps I'm missing something, but I was hoping these could be addressed somehow.

**Comment by petertseng** [comment]
Hmm, I think the main question here is whether a word is its own anagram. We can ask whether the no-op rearrangement is a rearrangement. In mathematics, the identity permutation is a permutation, but that is not the domain we're working in. I definitely see there could be arguments for either way, but at some point Exercism had to decide, and we made the choice that a word isn't its own anagram.

This is in agreement with the common test inputs/outputs at https://github.com/exercism/x-common/blob/master/anagram.json that all Exercism tracks are using.

So that explains why `test_does_not_detect_a_word_as_its_own_anagram` expects the output to be the empty vector. And since we know from an earlier test that the anagram check should be case-insensitive, the last two tests are just a combination of the "word isn't own anagram" and case insensitivity tests.

**Comment by erip** [comment]
@petertseng Excellent explanation. After some sleep it's becoming clearer why a word isn't its own anagram. I'll close this. Thanks!

**Comment by BartMassey** [comment]
@petertseng Both the case-insensitivity of anagrams and the rule that a word is not its own anagram should be mentioned in the problem description. The tests are fine: the description is missing important detail.

**Comment by petertseng** [comment]
You are correct that the problem description https://github.com/exercism/problem-specifications/blob/master/exercises/anagram/description.md does not say either of those things, and I agree with you that it would be an improvement (clearer to the student solving the problem) if it would say those two things.
